unit TestMoney;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Money;

const
  // The tests pin themselves to explicit locale ids so results do not depend on
  // the regional settings of whatever machine runs them. Nothing here should
  // read the user default.
  LCID_US = 1033;
  LCID_GB = 2057;
  LCID_FR = 1036;
  LCID_DE = 1031;
  LCID_SE = 1053;
  LCID_JP = 1041;
  LCID_CA = 4105;

type
  // Test methods for class TMoney
  TestTMoney = class(TTestCase)
  strict private
    FMoney: IMoney;
  public
    procedure SetUp; override;
  published
    procedure TestToString;
    procedure TestAdd;
    procedure TestSubtract;
    procedure TestMultiply;
    procedure TestAllocate;
    procedure TestEquals;
    procedure TestChangeCurrencyConstructorGBPtoUSD;
    procedure TestChangeCurrencyConstructorUSDtoGBP;
    procedure TestJBConversion;
    procedure TestChangeCurrencyRescalesMinorUnits;
    procedure TestAddDifferentCurrenciesRaises;
    procedure TestAllocateNegativeAmountKeepsEveryUnit;
    procedure TestAllocateRejectsEmptyAndZeroRatios;
    procedure TestAllocateHandlesAmountsPastIntegerRange;
    procedure TestMultiplyPastIntegerRange;
    procedure TestConstructorRoundsRatherThanTruncates;
    procedure TestRejectsUnsupportedCurrencyDecimals;
    procedure TestFromLocaleCarriesIsoCode;
    procedure TestCurrencyCodeSeparatesDollarCurrencies;
    procedure TestCurrencyCodeSurvivesArithmetic;
    procedure TestChangeCurrencyCarriesTargetCode;
    procedure TestRejectsEmptyCurrencyCode;
    procedure TestDivide;
    procedure TestDivideByZeroRaises;
    procedure TestDivideDoesNotConserveButAllocateDoes;
    procedure TestNegate;
    procedure TestCompareToAndOrdering;
    procedure TestCompareToDifferentCurrenciesRaises;
  end;

  //Test Allocating money
  TestAllocatingMoney = class(TTestCase)
  strict private
    FMoney: IMoney;
  public
    procedure SetUp; override;
  published
    procedure TestAllocate5050;
    procedure TestAllocate3070;
  end;

  //check the formatting for different currencies
  TestBritishMoney = class(TTestCase)
  strict private
    FMoney: IMoney;
  public
    procedure SetUp; override;
  published
    procedure TestToString;
  end;

  TestFrenchMoney = class(TTestCase)
  strict private
    FMoney: IMoney;
  public
    procedure SetUp; override;
  published
    procedure TestToString;
  end;

  TestGermanMoney = class(TTestCase)
  strict private
    FMoney: IMoney;
  public
    procedure SetUp; override;
  published
    procedure TestToString;
  end;

  TestSwedishMoney = class(TTestCase)
  strict private
    FMoney: IMoney;
  public
    procedure SetUp; override;
  published
    procedure TestToString;
  end;

implementation

uses
  Spring.Collections;

procedure TestTMoney.SetUp;
begin
  FMoney := TMoney.FromLocale(45.34, LCID_US);
end;

procedure TestTMoney.TestToString;
var
  ReturnValue: string;
begin
  ReturnValue := FMoney.ToString;
  Check(ReturnValue = '$45.34');
  // TODO: Validate method results
end;

procedure TestTMoney.TestAdd;
var
  ReturnValue: IMoney;
begin
  ReturnValue := FMoney.Add(TMoney.FromLocale(50.29, LCID_US));
  Check(ReturnValue.Amount = 9563);
end;

procedure TestTMoney.TestSubtract;
var
  ReturnValue: IMoney;
  Amount: IMoney;
begin
  Amount := TMoney.FromLocale(30.03, LCID_US);
  ReturnValue := FMoney.Subtract(Amount);
  Check(ReturnValue.Amount = 1531);
end;

procedure TestTMoney.TestMultiply;
var
  ReturnValue: IMoney;
  Amount: Currency;
begin
  // TODO: Setup method call parameters
  Amount := 1.00;
  ReturnValue := FMoney.Multiply(Amount);
  // TODO: Validate method results
  Check(ReturnValue.DecimalAmount = FMoney.DecimalAmount, 'Multiply failed');
end;

procedure TestTMoney.TestAllocate;
var
  ReturnValue: IList<IMoney>;
  Ratios: array[0..1] of integer;
begin
  Ratios[0] := 7;
  Ratios[1] := 3;

  ReturnValue := FMoney.Allocate(Ratios);

  Check(ReturnValue.Items[0].Amount = 3174);
  Check(ReturnValue.Items[1].Amount = 1360);
end;

procedure TestTMoney.TestChangeCurrencyConstructorGBPtoUSD;
var
  FromMoney : IMoney;
  ToMoney : IMoney;
begin
  FromMoney := TMoney.FromLocale(36.48, LCID_GB);
  ToMoney := TMoney.ChangeCurrency(FromMoney, TFormatSettings.Create(LCID_US), 1.58, TMoney.CurrencyCodeOfLocale(LCID_US));
  //57.6384
  //5764
  CheckEquals(5764, ToMoney.Amount);
  CheckEqualsString('$57.64', ToMoney.ToString);
end;

procedure TestTMoney.TestChangeCurrencyConstructorUSDtoGBP;
var
  FromMoney : IMoney;
  ToMoney : IMoney;
begin
  FromMoney := TMoney.FromLocale(36.48, LCID_US);
  ToMoney := TMoney.ChangeCurrency(FromMoney, TFormatSettings.Create(LCID_GB), 1.58, TMoney.CurrencyCodeOfLocale(LCID_GB));
  CheckEquals(5764, ToMoney.Amount);
  CheckEqualsString('£57.64', ToMoney.ToString);
end;

procedure TestTMoney.TestEquals;
var
  ReturnValue : boolean;
  aMoney : IMoney;
begin
  aMoney := TMoney.FromLocale(45.34, LCID_US);
  ReturnValue := FMoney.Equals(aMoney);
  Check(ReturnValue);

  aMoney := nil;
  aMoney := TMoney.FromLocale(5.27, LCID_US);
  ReturnValue := FMoney.Equals(aMoney);
  CheckFalse(ReturnValue);

  aMoney := nil;
  aMoney := TMoney.FromLocale(5.27, LCID_GB);
  ReturnValue := FMoney.Equals(aMoney);
//  CheckException(ReturnValue);

end;

procedure TestTMoney.TestJBConversion;
var
  CRCSettings : TFormatSettings;
  CRC : IMoney;
  USD : IMoney;
begin
  // 135,102.13 colones at 492.57 CRC to the dollar is $274.28. Built from an
  // explicit TFormatSettings rather than a locale id so the test does not
  // depend on which locales the machine has.
  CRCSettings := TFormatSettings.Create(LCID_US);
  CRCSettings.CurrencyString := 'CRC';
  CRCSettings.CurrencyDecimals := 2;

  CRC := TMoney.Create(135102.13, 'CRC', CRCSettings);
  USD := TMoney.ChangeCurrency(CRC, TFormatSettings.Create(LCID_US), 1 / 492.57, TMoney.CurrencyCodeOfLocale(LCID_US));

  CheckEquals(Int64(27428), USD.Amount);
end;

procedure TestTMoney.TestConstructorRoundsRatherThanTruncates;
begin
  // 1.239 is 123.9 cents. Truncating gave 123, quietly discarding most of a
  // cent, while Multiply already rounded - so the same value built two ways
  // disagreed.
  CheckEquals(Int64(124), TMoney.FromLocale(1.239, LCID_US).Amount);
  CheckEquals(Int64(-124), TMoney.FromLocale(-1.239, LCID_US).Amount);
end;

procedure TestTMoney.TestRejectsUnsupportedCurrencyDecimals;
var
  Odd : TFormatSettings;
  M : IMoney;
begin
  // CurrencyDecimals is a Byte and Windows lets it run past the factor table.
  // The old code read whatever followed the table in memory and scaled by it.
  Odd := TFormatSettings.Create(LCID_US);
  Odd.CurrencyDecimals := 9;
  try
    M := TMoney.Create(1.00, 'USD', Odd);
    Fail(Format('9 currency decimals should raise, got %d', [M.Amount]));
  except
    on E: EArgumentException do
      ; // expected
  end;
end;

procedure TestTMoney.TestFromLocaleCarriesIsoCode;
begin
  CheckEqualsString('USD', TMoney.FromLocale(45.34, LCID_US).CurrencyCode);
  CheckEqualsString('GBP', TMoney.FromLocale(45.34, LCID_GB).CurrencyCode);
  CheckEqualsString('JPY', TMoney.FromLocale(45, LCID_JP).CurrencyCode);
end;

procedure TestTMoney.TestCurrencyCodeSeparatesDollarCurrencies;
var
  USD : IMoney;
  CAD : IMoney;
begin
  // en-US and en-CA are indistinguishable by symbol ('$'), decimals (2) and
  // CurrencyFormat (0). The ISO code is the only thing that tells them apart.
  USD := TMoney.FromLocale(10.00, LCID_US);
  CAD := TMoney.FromLocale(10.00, LCID_CA);

  CheckEqualsString(USD.FormatSettings.CurrencyString,
    CAD.FormatSettings.CurrencyString,
    'this test only means anything while both locales share a symbol');
  CheckEqualsString('USD', USD.CurrencyCode);
  CheckEqualsString('CAD', CAD.CurrencyCode);

  try
    USD.Add(CAD);
    Fail('adding CAD to USD should raise ECurrencyCodeMismatch');
  except
    on E: ECurrencyCodeMismatch do
      ; // expected
  end;

  CheckFalse(USD.Equals(CAD), 'USD 10 and CAD 10 are not equal');
end;

procedure TestTMoney.TestCurrencyCodeSurvivesArithmetic;
var
  GBP : IMoney;
  Shares : IList<IMoney>;
  Ratios : array[0..1] of integer;
begin
  GBP := TMoney.FromLocale(10.00, LCID_GB);

  CheckEqualsString('GBP', GBP.Multiply(2).CurrencyCode, 'Multiply');
  CheckEqualsString('GBP', GBP.Add(TMoney.FromLocale(5.00, LCID_GB)).CurrencyCode, 'Add');

  Ratios[0] := 1;
  Ratios[1] := 1;
  Shares := GBP.Allocate(Ratios);
  CheckEqualsString('GBP', Shares.Items[0].CurrencyCode, 'Allocate');
end;

procedure TestTMoney.TestChangeCurrencyCarriesTargetCode;
var
  USD : IMoney;
  JPY : IMoney;
begin
  USD := TMoney.FromLocale(10.00, LCID_US);
  JPY := TMoney.ChangeCurrency(USD, TFormatSettings.Create(LCID_JP), 150,
    TMoney.CurrencyCodeOfLocale(LCID_JP));

  CheckEqualsString('JPY', JPY.CurrencyCode);
  CheckEquals(Int64(1500), JPY.Amount);
end;

procedure TestTMoney.TestRejectsEmptyCurrencyCode;
var
  M : IMoney;
begin
  // The code is the currency identity now, so allowing an empty one would put
  // us straight back to TFormatSettings, which cannot tell USD from CAD.
  try
    M := TMoney.Create(1.00, '', TFormatSettings.Create(LCID_US));
    Fail(Format('an empty currency code should raise, got %d', [M.Amount]));
  except
    on E: EArgumentException do
      ; // expected
  end;
end;

procedure TestTMoney.TestDivide;
var
  M : IMoney;
begin
  M := TMoney.FromLocale(10.00, LCID_US);
  CheckEquals(Int64(250), M.Divide(4).Amount, '$10.00 / 4');
  CheckEquals(Int64(333), M.Divide(3).Amount, '$10.00 / 3 rounds to the cent');
  CheckEqualsString('USD', M.Divide(4).CurrencyCode, 'the code survives');
end;

procedure TestTMoney.TestDivideByZeroRaises;
var
  M : IMoney;
  R : IMoney;
begin
  M := TMoney.FromLocale(10.00, LCID_US);
  try
    R := M.Divide(0);
    Fail(Format('dividing by zero should raise, got %d', [R.Amount]));
  except
    on E: EArgumentException do
      ; // expected
  end;
end;

procedure TestTMoney.TestDivideDoesNotConserveButAllocateDoes;
var
  Dollar : IMoney;
  Shares : IList<IMoney>;
  Ratios : array[0..2] of integer;
  Total : Int64;
  i : Integer;
begin
  // Divide rounds each part on its own, so the parts need not add back up to
  // the whole. That is exactly why Allocate exists. Pinning both behaviours
  // here so neither gets "fixed" into the other.
  Dollar := TMoney.FromLocale(1.00, LCID_US);

  CheckEquals(Int64(33), Dollar.Divide(3).Amount, 'a third of a dollar');
  CheckEquals(Int64(99), Dollar.Divide(3).Multiply(3).Amount,
    'three thirds are a cent short of the whole');

  Ratios[0] := 1;
  Ratios[1] := 1;
  Ratios[2] := 1;
  Shares := Dollar.Allocate(Ratios);

  Total := 0;
  for i := 0 to Shares.Count - 1 do
    Total := Total + Shares.Items[i].Amount;
  CheckEquals(Int64(100), Total, 'Allocate conserves the whole');
end;

procedure TestTMoney.TestNegate;
var
  M : IMoney;
begin
  M := TMoney.FromLocale(45.34, LCID_US);

  CheckEquals(Int64(-4534), M.Negate.Amount);
  CheckEquals(Int64(4534), M.Negate.Negate.Amount, 'negation is its own inverse');
  CheckEqualsString('USD', M.Negate.CurrencyCode, 'the code survives');
  CheckEquals(Int64(0), M.Add(M.Negate).Amount, 'a value plus its negation is zero');
end;

procedure TestTMoney.TestCompareToAndOrdering;
var
  Small : IMoney;
  Big : IMoney;
begin
  Small := TMoney.FromLocale(5.00, LCID_US);
  Big := TMoney.FromLocale(10.00, LCID_US);

  CheckEquals(-1, Small.CompareTo(Big), 'less');
  CheckEquals(1, Big.CompareTo(Small), 'greater');
  CheckEquals(0, Big.CompareTo(TMoney.FromLocale(10.00, LCID_US)), 'equal');

  Check(Small.LessThan(Big), 'LessThan');
  Check(Big.GreaterThan(Small), 'GreaterThan');
  CheckFalse(Big.LessThan(Small), 'not LessThan');
  CheckFalse(Small.GreaterThan(Big), 'not GreaterThan');
end;

procedure TestTMoney.TestCompareToDifferentCurrenciesRaises;
var
  USD : IMoney;
  GBP : IMoney;
begin
  // Equals answers False across currencies - they are certainly not equal.
  // Which one is greater is not a question with an answer, so CompareTo
  // raises rather than inventing one.
  USD := TMoney.FromLocale(10.00, LCID_US);
  GBP := TMoney.FromLocale(10.00, LCID_GB);

  CheckFalse(USD.Equals(GBP), 'Equals answers False');

  try
    USD.CompareTo(GBP);
    Fail('comparing USD with GBP should raise ECurrencyCodeMismatch');
  except
    on E: ECurrencyCodeMismatch do
      ; // expected
  end;
end;

procedure TestTMoney.TestChangeCurrencyRescalesMinorUnits;
var
  USD : IMoney;
  JPY : IMoney;
begin
  // USD carries two minor-unit digits, JPY none, so the raw amounts are on
  // different scales. $10.00 at 150 JPY/USD is 1500 yen, not 150000.
  USD := TMoney.FromLocale(10.00, LCID_US);
  JPY := TMoney.ChangeCurrency(USD, TFormatSettings.Create(LCID_JP), 150, TMoney.CurrencyCodeOfLocale(LCID_JP));
  CheckEquals(0, JPY.FormatSettings.CurrencyDecimals, 'JPY should have no minor unit');
  CheckEquals(1500, JPY.Amount);
end;

procedure TestTMoney.TestAddDifferentCurrenciesRaises;
var
  GBP : IMoney;
begin
  // CurrencyFormat is 0 for both en-US and en-GB, so the old guard compared
  // equal and let this addition through.
  GBP := TMoney.FromLocale(10.00, LCID_GB);
  try
    FMoney.Add(GBP);
    Fail('Adding GBP to USD should raise ECurrencyCodeMismatch');
  except
    on E: ECurrencyCodeMismatch do
      ; // expected
  end;
end;

procedure TestTMoney.TestAllocateNegativeAmountKeepsEveryUnit;
var
  Debt : IMoney;
  Shares : IList<IMoney>;
  Ratios : array[0..1] of integer;
begin
  // -101 cents split evenly. Truncating division handed out -50 and -50 and
  // quietly dropped a cent; flooring hands out -50 and -51.
  Debt := TMoney.FromLocale(-1.01, LCID_US);
  Ratios[0] := 1;
  Ratios[1] := 1;

  Shares := Debt.Allocate(Ratios);

  CheckEquals(Int64(-101), Shares.Items[0].Amount + Shares.Items[1].Amount,
    'the shares must add back up to the whole');
  CheckEquals(Int64(-50), Shares.Items[0].Amount);
  CheckEquals(Int64(-51), Shares.Items[1].Amount);
end;

procedure TestTMoney.TestAllocateRejectsEmptyAndZeroRatios;
var
  Empty : array of integer;
  Zeros : array[0..1] of integer;
begin
  // Previously: empty ratios indexed an empty list, zero-sum ratios divided
  // by zero.
  SetLength(Empty, 0);
  try
    FMoney.Allocate(Empty);
    Fail('empty ratios should raise EArgumentException');
  except
    on E: EArgumentException do
      CheckFalse(E is EArgumentOutOfRangeException,
        'the guard should raise deliberately, not fail on an index');
  end;

  Zeros[0] := 0;
  Zeros[1] := 0;
  try
    FMoney.Allocate(Zeros);
    Fail('zero-sum ratios should raise EArgumentException');
  except
    on E: EArgumentException do
      CheckFalse(E is EArgumentOutOfRangeException,
        'the guard should raise deliberately, not fail on an index');
  end;
end;

procedure TestTMoney.TestAllocateHandlesAmountsPastIntegerRange;
var
  Big : IMoney;
  Shares : IList<IMoney>;
  Ratios : array[0..1] of integer;
begin
  // $1,000,000.00 is 100,000,000 cents; times ratio 30 is 3e9, which overflowed
  // the old 32-bit intermediate and produced negative shares.
  Big := TMoney.FromLocale(1000000.00, LCID_US);
  Ratios[0] := 30;
  Ratios[1] := 70;

  Shares := Big.Allocate(Ratios);

  CheckEquals(Int64(30000000), Shares.Items[0].Amount);
  CheckEquals(Int64(70000000), Shares.Items[1].Amount);
end;

procedure TestTMoney.TestMultiplyPastIntegerRange;
var
  Big : IMoney;
begin
  // 1e9 cents times 3 is 3e9, past what the old Integer amount could hold.
  Big := TMoney.FromLocale(10000000.00, LCID_US);
  CheckEquals(Int64(3000000000), Big.Multiply(3).Amount);
end;

{ TestBritishMoney }

procedure TestBritishMoney.SetUp;
begin
  FMoney := TMoney.FromLocale(45.34, LCID_GB);
end;

procedure TestBritishMoney.TestToString;
var
  ReturnValue: string;
begin
  ReturnValue := FMoney.ToString;
  Check(ReturnValue = '£45.34');
end;

{ TestFrenchMoney }

procedure TestFrenchMoney.SetUp;
begin
  FMoney := TMoney.FromLocale(45.34, LCID_FR);
end;

procedure TestFrenchMoney.TestToString;
var
  ReturnValue: string;
begin
  ReturnValue := FMoney.ToString;
  Check(ReturnValue = '45,34 €');
end;

{ TestGermanMoney }

procedure TestGermanMoney.SetUp;
begin
  FMoney := TMoney.FromLocale(45.34, LCID_DE);
end;

procedure TestGermanMoney.TestToString;
var
  ReturnValue: string;
begin
  ReturnValue := FMoney.ToString;
  Check(ReturnValue = '45,34 €');
end;

{ TestSwedishMoney }

procedure TestSwedishMoney.SetUp;
begin
  FMoney := TMoney.FromLocale(45.34, LCID_SE);
end;

procedure TestSwedishMoney.TestToString;
var
  ReturnValue: string;
begin
  ReturnValue := FMoney.ToString;
  Check(ReturnValue = '45,34 kr');
end;

{ TestAllocatingMoney }

procedure TestAllocatingMoney.SetUp;
begin
  FMoney := TMoney.FromLocale(0.05, LCID_US);
end;

procedure TestAllocatingMoney.TestAllocate3070;
var
  ReturnValue: IList<IMoney>;
  Ratios: array[0..1] of integer;
begin
  Ratios[0] := 3;
  Ratios[1] := 7;

  ReturnValue := FMoney.Allocate(Ratios);

  Check(ReturnValue.Items[0].Amount = 2);
  Check(ReturnValue.Items[1].Amount = 3);
end;

procedure TestAllocatingMoney.TestAllocate5050;
var
  ReturnValue: IList<IMoney>;
  Ratios: array[0..1] of integer;
begin
  Ratios[0] := 5;
  Ratios[1] := 5;

  ReturnValue := FMoney.Allocate(Ratios);

  Check(ReturnValue.Items[0].Amount = 3);
  Check(ReturnValue.Items[1].Amount = 2);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTMoney.Suite);
  RegisterTest(TestBritishMoney.Suite);
  RegisterTest(TestFrenchMoney.Suite);
  RegisterTest(TestGermanMoney.Suite);
  RegisterTest(TestSwedishMoney.Suite);
  RegisterTest(TestAllocatingMoney.Suite);

end.

